/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.io.File;
import java.io.IOException;
import javafx.embed.swing.JFXPanel;
import javafx.scene.media.MediaPlayer;

/**
 * Video frame
 *
 * @author sergi
 */
public class VideoFrame extends javax.swing.JFrame {

    private MediaPlayer mediaPlayer;
    private final String selectedVideo;

    private final JFXPanel jfxpanel = new JFXPanel();

    /**
     * Videoframe constructor.
     *
     * @param selectedVideo
     */
    public VideoFrame(String selectedVideo) {
        this.selectedVideo = selectedVideo;
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("Reproduciendo " + selectedVideo);
        File file = new File("descargas/" + selectedVideo);

        if (file != null) {
            String relativePath = file.toURI().toString();

            String absolutePath = relativePath.substring(6);

            System.out.println("direccion del archivo: " + absolutePath);// Ruta relativa al archivo de video en tu proyecto

            playVideoWithWindowsMediaPlayer(absolutePath);
        }

        setResizable(false);
        setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);

        videoName.setText(selectedVideo);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                stopVideo();
                dispose();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        videoName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        videoName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        videoName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        videoName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(videoName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(videoName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel videoName;
    // End of variables declaration//GEN-END:variables
/**
     * Plays the video on media player.
     *
     * @param videoFilePath
     */
    public static void playVideoWithWindowsMediaPlayer(String videoFilePath) {
        System.out.println(videoFilePath);
        try {
            File videoFile = new File(videoFilePath);
            if (!videoFile.exists()) {
                System.out.println("El archivo de video no existe: " + videoFilePath);
                return;
            }

            ProcessBuilder builder = new ProcessBuilder("cmd.exe", "/c", "start", "wmplayer", videoFilePath);
            builder.start();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Closes the media player.
     */
    private void stopVideo() {
        if (mediaPlayer != null) {
            mediaPlayer.stop();
            mediaPlayer.dispose();
        }
    }
}
